### ISSUE TITLE
Cannot Parse BET365 and UniBet

### ISSUE THREAD

**Issue by cardchase** [S1M0N38/soccerapi#30]
As of yesterday,
I am trying to parse BET365 however unsuccessful.
Can you please help me if I am missing anything.
![Cannot Parse](https://user-images.githubusercontent.com/33249394/106549422-01b9fb00-6565-11eb-837d-dbe039586c15.PNG)

**Comment by xhantos** [comment]
The urls to pass to obtain bet365 odds are not the same anymore since the last commits. In the "competitions" branch we're introducing a method called "competition" for every bookmaker class which returns a list of the competitions available for the bookmaker with the relative url. By the way the new work around to get the 'x-net-sync-term' header of bet365 it's not perfect: try to create new objects of the ApiBet365 class as less frequent as you can. Every time you create a ApiBet365 object it will ask bet365 to get that header and if you do it too often (more than once every 10 minutes) they will block your IP.
